login_box.html
=> Username and Pass box

login_box.html
=> add cancel in html

stack_overfull/frontend/.gitignore, stack_overfull/frontend/package.json, stack_overfull/frontend/templates/index.html, stack_overfull/frontend/webpack-stats.json, stack_overfull/frontend/webpack.config.js, stack_overfull/so_endpoint/urls.py
- api/ endpoint serves a blank html file
- Webpack configured for the react app
- Added a few lines in the gitignore
- Updated npm dependencies
=> Backend now serves an html file

stack_overfull/so_endpoint/urls.py, stack_overfull/so_endpoint/views.py
- Backend can now register and authenticate users
- Made several new url endpoints for communication with the frontend
- Stored users can now be listed at api/user/
- The currently logged in user can be retrieved at api/user/me/
=> User registration/authentication Issue #20

stack_overfull/frontend/src/index.js, stack_overfull/frontend/templates/index.html, stack_overfull/frontend/webpack-stats.json
- Developers can now use yarn start to run the react app locally
=> Fixed bug with yarn start #36

stack_overfull/frontend/src/components/AcceptRejectButton/index.jsx
Changed the accept/reject buttons and prompts to make them look more user-friendly.
=> Accept/Reject Prompt Buttons Version 2

stack_overfull/so_endpoint/views.py
- The answer and question get request now accepts an extra parameter to use for sorting
=> Sort get request by any field #76

stack_overfull/frontend/webpack-stats.json, stack_overfull/so_endpoint/serializers.py
- Backend no longer throws exception while serializing a profile
=> Fixed bug #82

stack_overfull/so_endpoint/tests.py
- added test cases for user views
=> Added several test cases for backend task #99

stack_overfull/so_endpoint/serializers.py, stack_overfull/so_endpoint/tests.py, stack_overfull/so_endpoint/urls.py, stack_overfull/so_endpoint/views.py, stack_overfull/stack_overfull/urls.py
Added backend code for search User story #28
- added search/ endpoint for the search page
- added SearchView and api/search/ ednpoint task #94
- removed user_dict serializer and replaced with AccountSerializer bug #82
- changed UserView to return a user_list object instead of an array
=> Added backend code for search User story #28

stack_overfull/so_endpoint/tests.py, stack_overfull/so_endpoint/views.py
- Added unit test for question and answer endpoints
=> Backend testing

stack_overfull/so_endpoint/serializers.py, stack_overfull/so_endpoint/urls.py, stack_overfull/so_endpoint/views.py
Improved user/ endpoints task #124
- added POST method to api/user/me/ to modify the user information
- added api/user/name/<username>/ endpoint to get user's information by username
- added 'inname', 'limit', 'order' and 'sort' optional parameters to api/user/
=> User profile edit

.travis.yml, build.sh, stack_overfull/frontend/package.json, stack_overfull/frontend/yarn.lock
- Travis now runs frontend tests after pushes
=> Set up Travis CI for frontend #131

stack_overfull/so_endpoint/models.py, stack_overfull/so_endpoint/serializers.py, stack_overfull/so_endpoint/views.py
- Refactored to avoid wildcard imports
- Added a few comments to improve clarity
- Changed code to not have empty exceptions
- Removed unnecessary imports
=> Refactoring

stack_overfull/frontend/src/components/QuestionBox/index.css, stack_overfull/frontend/src/components/QuestionBox/index.jsx, stack_overfull/frontend/src/pages/AnswerPage/index.jsx
- Combined the username and date on the same line
- Added a switch statement to convert the month number to text
- Added a switch statement to add suffix for the days
- Made the question bigger
=> Changed the ui of the question box on the top questions page

stack_overfull/frontend/src/components/QuestionBox/index.css, stack_overfull/frontend/src/components/QuestionBox/index.jsx, stack_overfull/frontend/src/components/VotingButtons/index.css, stack_overfull/frontend/src/components/VotingButtons/index.jsx
Users can now vote on questions, which will allow questions to be "trending" on the home page (sorted based on number of points).
Styling is also changed to enhance the overall look of the website.
=> #110 improved styling of voting buttons

stack_overfull/so_endpoint/tests.py
- added backend tests for api/user/ api/answer/accept/ api/answer/reject/ api/search/
=>  Additional tests for backend enhancement #99

stack_overfull/frontend/webpack.config.js
=> Set up react hot reloading #187

stack_overfull/so_endpoint/tests.py, stack_overfull/so_endpoint/views.py
- Users can revert their vote by upvoting/downvoting twice
- Adjusted tests to this change
=> Users can revert their vote #180

buildserve.sh, pytest.py, stack_overfull/so_endpoint/tests.py, stack_overfull/so_endpoint/urls.py, stack_overfull/so_endpoint/views.py
- Created url endpoint that returns 2 lists of questions: the first is a list of questions asked by the user and the second is a list of questions answered by the user.
- Added tests for this new endpoint
=> Profile backend

stack_overfull/so_endpoint/tests.py, stack_overfull/so_endpoint/views.py
- Users can no longer vote on their own questions and answers
- Added some more backend test cases to increase code coverage
=> Users can no longer vote on their own questions and answers

stack_overfull/so_endpoint/views.py
- Backend now sends list of upvoted and downvoted questions
=> Improved profile backend #203

stack_overfull/frontend/package.json, stack_overfull/frontend/src/App.css, stack_overfull/frontend/src/components/JobBox/index.css, stack_overfull/frontend/src/components/JobBox/index.jsx, stack_overfull/frontend/src/components/JobList/index.css, stack_overfull/frontend/src/components/NavigationBar/index.jsx, stack_overfull/frontend/src/components/QuestionList/index.css, stack_overfull/frontend/src/components/SideBar/index.css, stack_overfull/frontend/src/components/SideBar/index.jsx, stack_overfull/frontend/src/pages/CareerPage/index.css, stack_overfull/frontend/src/pages/CareerPage/index.jsx, stack_overfull/frontend/src/pages/CategoryListPage/index.jsx, stack_overfull/frontend/src/pages/HomePage/index.css, stack_overfull/frontend/src/pages/HomePage/index.jsx, stack_overfull/frontend/yarn.lock
- I moved new job button to the right
- add some css for overall website design
- fixed job description overflow
=> impoved carrier page design #95

stack_overfull/frontend/src/components/AnswerBox/index.jsx, stack_overfull/frontend/src/components/QuestionBox/index.jsx, stack_overfull/frontend/src/components/QuestionList/index.jsx, stack_overfull/frontend/src/components/VotingButtons/index.css, stack_overfull/frontend/src/components/VotingButtons/index.jsx, stack_overfull/frontend/src/pages/AnswerPage/index.css, stack_overfull/frontend/src/pages/AnswerPage/index.jsx, stack_overfull/frontend/src/utils/api.js
- Updated voting buttons style
- Users can now vote on a question from the AnswerPage
=> #164 Updated voting on questions

stack_overfull/frontend/src/pages/ProfilePage/index.jsx, stack_overfull/frontend/src/utils/api.js
Adding edition to the profile page User story #152 task #157
- added first and last name to the profile page
- added postApiUserMe() to the api.js file
- made some fields modifiable on the profile page
=> Adding edition to the profile page User story #152 task #157

stack_overfull/frontend/src/components/SearchBar/index.jsx, stack_overfull/frontend/src/pages/ProfilePage/index.jsx, stack_overfull/frontend/src/pages/SearchPage/index.jsx
Preserve search text on the SearchPage
- replaced \<Redirect\> with history.push()
- added preserveInput prop to the searchbar
- fixed #205
=> Preserve search text on the searchpage

stack_overfull/frontend/src/pages/ProfilePage/index.jsx
- Added code to retrieve upvoted/downvoted questions from database
- Removed unused code
=> Enhancement for upvoted/downvoted questions

stack_overfull/frontend/src/components/Footer/index.css, stack_overfull/frontend/src/components/Footer/index.jsx, stack_overfull/frontend/src/components/Footer/index.test.js, stack_overfull/frontend/src/components/SearchBar/index.jsx, stack_overfull/frontend/src/pages/CategoryListPage/index.css, stack_overfull/frontend/src/pages/CategoryListPage/index.jsx, stack_overfull/frontend/src/pages/TagPage/index.css, stack_overfull/frontend/src/pages/TagPage/index.jsx
Enhancement on Footer #218 
- Removed dead links
- Linked About and Help tabs to hrefs
Fix Search Button #219
- Search button now works and links to search query
=> Footer enhancement and Fix for Search Button

stack_overfull/frontend/src/components/SignUpForm/index.jsx, stack_overfull/frontend/src/utils/api.js, stack_overfull/so_endpoint/views.py
- Added a dropdown to select type of account during registration
- Changed backend to accomodate this change
=> Employer accounts can now get created #223

stack_overfull/so_endpoint/views.py
- Improved code quality by fixing errors shown by pylint
=> Fixed pylint warnings #227

stack_overfull/frontend/src/components/JobBox/index.jsx, stack_overfull/frontend/src/components/JobList/index.jsx, stack_overfull/frontend/src/pages/ProfilePage/index.jsx, stack_overfull/frontend/src/utils/api.js
- added apply button #182
- added list of applicants on profile page #152
=> Apply button and applicant list

stack_overfull/so_endpoint/views.py
- Employers can no longer apply to jobs
- Users can no longer apply to the same job multiple times
=> Fixed bugs #230

stack_overfull/frontend/src/components/UserInfo/index.jsx, stack_overfull/frontend/src/pages/ProfilePage/index.jsx, stack_overfull/frontend/src/pages/UserPage/index.jsx, stack_overfull/frontend/src/utils/api.js, stack_overfull/so_endpoint/views.py
Profile github/linkedin fields
- added github/linkedin fields to the user/me/ endpoint
- added github/linkedin to apiPostUserMe()
- added github/linkedin fields to UserInfo
- changed UserInfo to hide empty fields
- added activity indicator beside username
-
=> Profile github/linkedin fields

stack_overfull/frontend/src/components/ProfileTabs/index.jsx, stack_overfull/frontend/src/components/UserInfo/index.css, stack_overfull/frontend/src/components/UserInfo/index.jsx, stack_overfull/frontend/src/components/UserQuestionList/index.css, stack_overfull/frontend/src/components/UserQuestionList/index.jsx, stack_overfull/frontend/src/components/index.js, stack_overfull/frontend/src/pages/ProfilePage/index.css, stack_overfull/frontend/src/pages/ProfilePage/index.jsx
-Added a new component for tabs in the profile page
-Added tabs for the different type of questions
-Modified the ui for profile information and the type of questions
-Added a route for profile tabs component
-Added code for handling the change of tabs in profile page
-Added a box for the user information
-Added an if statement to show a message when not logged in
=> Enhancement for the profile page

stack_overfull/so_endpoint/tests.py, stack_overfull/so_endpoint/views.py
- Added PUT and DELETE methods in the question and answer endpoints to handle question/answer edits and deletions
=> Edit delete

stack_overfull/frontend/src/App.css, stack_overfull/frontend/src/components/AnswerBox/index.css, stack_overfull/frontend/src/components/AnswerBox/index.jsx, stack_overfull/frontend/src/pages/AnswerPage/index.css, stack_overfull/frontend/src/pages/AnswerPage/index.jsx, stack_overfull/frontend/src/utils/api.js
- User can delete their own question
- User can delete their own answer
=> #252 Delete functionality completed

stack_overfull/frontend/src/components/AcceptRejectButton/index.jsx, stack_overfull/so_endpoint/tests/test_answer.py, stack_overfull/so_endpoint/urls.py, stack_overfull/so_endpoint/views.py
- Merged undo accept and accept into 1 url
- Merged undo reject and reject into 1 url
- Added undo button when users accept/reject
=> Allowed users to undo their accept/reject #240

stack_overfull/frontend/src/App.css, stack_overfull/frontend/src/App.jsx, stack_overfull/frontend/src/components/UserInfo/index.jsx, stack_overfull/frontend/src/pages/UserPage/index.jsx
- Does a check before showing the edit button on user page
- Added bottom padding in body wrapper
=> Removed edit button on other user's pages #235

stack_overfull/frontend/src/components/SignInForm/index.jsx
- Removed the "Remember me?" checkbox in the login form
=> Removed useless links #243

stack_overfull/frontend/src/App.jsx, stack_overfull/frontend/src/components/UserInfo/index.jsx, stack_overfull/frontend/src/components/UserQuestionList/index.jsx, stack_overfull/frontend/src/pages/ProfilePage/index.jsx, stack_overfull/frontend/src/pages/UserPage/index.jsx, stack_overfull/frontend/src/utils/api.js
- fixed user page #260 
- formatted some code in api.js
=> Fixed user page
